refactor: separate component directories and alias imports (#343)
The components cannot currently be imported for testing because you get
`YextEntityFieldSelector is not a function.
src/components/puck/Address.tsx:25:12` no matter what component you
test. This is caused by an issue with dependency loading -- I think it's
because things in the `utils` folder use things in the
`components/editor` folder and vice versa. By separating
`components/editor` and `components/puck`, all the puck component
dependencies can get resolved first.

This also adds aliasing so you can use `"@yext/visual-editor"` instead
of `"../../index.js"`